name: sky_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.11.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  
  #Storage
  shared_preferences: 2.5.5
  flutter_secure_storage: 10.0.0
  cached_network_image_ce: 4.6.4

  #State Management
  provider: 6.1.5+1

  #Routing
  go_router: 17.1.0

  #UI
  flutter_svg: 2.2.4
  carousel_slider: 5.1.2
  phosphor_flutter: 2.1.0
  timeago: 3.7.1

  #Web & External Links
  dio: 5.9.2
  webview_flutter: 4.8.0
  url_launcher: 6.3.0

  #QR Code Scanner
  mobile_scanner: 7.2.0

  #Permissions
  permission_handler: 12.0.1

  #Auth
  flutter_appauth: 12.0.0
  crypto: ^3.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
